object = "<function my_func at 0x7fa306d0d040>"
type = "function"
serializable_by_default = false
name = "my_func"
code = [ "def my_func(a, b):", "    return (a * b) ** 2", "",]
base64 = "gASVHQAAAAAAAACMDXRlc3Rfc3RhcnRhcHCUjAdteV9mdW5jlJOULg=="

[dict_class]

[args]
args = [ "a", "b",]
kwonlyargs = []

[args.annotations]
